resolver: lts-15.12
extra-deps:
- git: https://github.com/mbj/source-constraints
  commit: 882efed7bef03fcc92985b1e76c0056731739e82
- git: https://github.com/feuerbach/tasty
  commit: 2ff2bda960061226d73b0b166006aff6ea6c04da
  subdirs:
  - core
